#-------------------------sys_input---------------------------------
#set UnusedPin
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]

#system slock
set_property PACKAGE_PIN y9 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

#reset active low,S0
set_property PACKAGE_PIN h18 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
#-------------------------------------------------------------------

#----------------5��TFT��ģ�飨ʹ����չ��GPIO2��--------------------
#TFT
set_property PACKAGE_PIN v22 [get_ports TFT_clk]
set_property PACKAGE_PIN ab19 [get_ports TFT_de]
set_property PACKAGE_PIN u19 [get_ports TFT_pwm]
set_property PACKAGE_PIN ab14 [get_ports TFT_hs]
set_property PACKAGE_PIN u14 [get_ports TFT_vs]
set_property PACKAGE_PIN ab21 [get_ports {TFT_rgb[15]}]
set_property PACKAGE_PIN aa17 [get_ports {TFT_rgb[14]}]
set_property PACKAGE_PIN ab17 [get_ports {TFT_rgb[13]}]
set_property PACKAGE_PIN aa16 [get_ports {TFT_rgb[12]}]
set_property PACKAGE_PIN ab16 [get_ports {TFT_rgb[11]}]
set_property PACKAGE_PIN y13  [get_ports {TFT_rgb[10]}]
set_property PACKAGE_PIN aa13 [get_ports {TFT_rgb[9]}]
set_property PACKAGE_PIN w22  [get_ports {TFT_rgb[8]}]
set_property PACKAGE_PIN aa22 [get_ports {TFT_rgb[7]}]
set_property PACKAGE_PIN ab22 [get_ports {TFT_rgb[6]}]
set_property PACKAGE_PIN aa21 [get_ports {TFT_rgb[5]}]
set_property PACKAGE_PIN ab15 [get_ports {TFT_rgb[4]}]
set_property PACKAGE_PIN w13  [get_ports {TFT_rgb[3]}]
set_property PACKAGE_PIN v13  [get_ports {TFT_rgb[2]}]
set_property PACKAGE_PIN v15  [get_ports {TFT_rgb[1]}]
set_property PACKAGE_PIN v14  [get_ports {TFT_rgb[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports TFT_clk]
set_property IOSTANDARD LVCMOS33 [get_ports TFT_de]
set_property IOSTANDARD LVCMOS33 [get_ports TFT_pwm]
set_property IOSTANDARD LVCMOS33 [get_ports TFT_hs]
set_property IOSTANDARD LVCMOS33 [get_ports TFT_vs]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TFT_rgb[0]}]
#-------------------------------------------------------------------



set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports SiI9022_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports SiI9022_sdat]
set_property PACKAGE_PIN p20 [get_ports led]
set_property PACKAGE_PIN g22 [get_ports SiI9022_sclk]
set_property PACKAGE_PIN h22 [get_ports SiI9022_sdat]



#--------------------------------------------------------------------------------------------
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DataB[0]}]

set_property PACKAGE_PIN U11 [get_ports {DataA[13]}]
set_property PACKAGE_PIN U12 [get_ports {DataA[12]}]
set_property PACKAGE_PIN U9 [get_ports {DataA[11]}]
set_property PACKAGE_PIN U10 [get_ports {DataA[10]}]
set_property PACKAGE_PIN Y10 [get_ports {DataA[9]}]
set_property PACKAGE_PIN Y11 [get_ports {DataA[8]}]
set_property PACKAGE_PIN W7 [get_ports {DataA[7]}]
set_property PACKAGE_PIN V7 [get_ports {DataA[6]}]
set_property PACKAGE_PIN Y5 [get_ports {DataA[5]}]
set_property PACKAGE_PIN Y6 [get_ports {DataA[4]}]
set_property PACKAGE_PIN U5 [get_ports {DataA[3]}]
set_property PACKAGE_PIN U6 [get_ports {DataA[2]}]
set_property PACKAGE_PIN V4 [get_ports {DataA[1]}]
set_property PACKAGE_PIN V5 [get_ports {DataA[0]}]
set_property PACKAGE_PIN V10 [get_ports {DataB[13]}]
set_property PACKAGE_PIN V9 [get_ports {DataB[12]}]
set_property PACKAGE_PIN V12 [get_ports {DataB[11]}]
set_property PACKAGE_PIN W12 [get_ports {DataB[10]}]
set_property PACKAGE_PIN AA12 [get_ports {DataB[9]}]
set_property PACKAGE_PIN AB12 [get_ports {DataB[8]}]
set_property PACKAGE_PIN AA11 [get_ports {DataB[7]}]
set_property PACKAGE_PIN AB11 [get_ports {DataB[6]}]
set_property PACKAGE_PIN V8 [get_ports {DataB[5]}]
set_property PACKAGE_PIN W8 [get_ports {DataB[4]}]
set_property PACKAGE_PIN AA7 [get_ports {DataB[3]}]
set_property PACKAGE_PIN AA6 [get_ports {DataB[2]}]
set_property PACKAGE_PIN AB10 [get_ports {DataB[1]}]
set_property PACKAGE_PIN AB9 [get_ports {DataB[0]}]
set_property PACKAGE_PIN Y9 [get_ports Clk]
set_property PACKAGE_PIN T4 [get_ports ClkA]
set_property PACKAGE_PIN R6 [get_ports ClkB]
set_property PACKAGE_PIN H18 [get_ports Reset_n]
set_property PACKAGE_PIN U4 [get_ports WRTA]
set_property PACKAGE_PIN T6 [get_ports WRTB]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports ClkA]
set_property IOSTANDARD LVCMOS33 [get_ports ClkB]
set_property IOSTANDARD LVCMOS33 [get_ports Reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports WRTA]
set_property IOSTANDARD LVCMOS33 [get_ports WRTB]




# 时钟路由约束
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_n_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_out]

# 如果需要，降低时序要求
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

